# This is a basic workflow to help you get started with Actions

name: webdav_lastsync

on:
  schedule:
    - cron: '0 4,16 * * *'
  workflow_dispatch:

jobs:
  fix-sync:
    runs-on: ubuntu-18.04
    steps:
      - name: Fix zotero sync
        run: |
          export SYNCFILE="lastsync.txt"
          export REMOTEFILE="http://xiedejia.6655.la:5005/webdav/Share/zotero/${SYNCFILE}"
          touch ${SYNCFILE}
          curl -u ${WEBDAV_EMAIL}:${WEBDAV_DAVPASS} -T ${SYNCFILE} ${REMOTEFILE}
        env:
          WEBDAV_EMAIL: ${{ secrets.WEBDAV_EMAIL }}
          WEBDAV_DAVPASS: ${{ secrets.WEBDAV_DAVPASS }}
